version: "3.8"
services:
  db:
    image: postgres
    container_name: psql-ultracar
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ultracardb
    volumes:
      - psql-ultracar:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'

volumes:
  psql-ultracar: